# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3440de029dd1a4ecd2403a6a5b1e551e9e126ff8d4a22a9c27326b315e86555174211732e65bb9d06f54e8cf8546d21e12f70f2c9f43c2d291d349996452b001

test:
  secret_key_base: 869d0639a38b396d20c1cfad623276ec363261ee70c712aae26528c587fe22ad20fe5d3b8ff7dfb876e2ac6260252119d56e6ebc235d0cd14e505599a0bb8c4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
